CREATE TABLE IF NOT EXISTS `file_data` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dataset_id` BIGINT(20) NOT NULL,
  `filename` VARCHAR(255),
  `ext` VARCHAR(255),
  `bytes` INT,
  `used` TINYINT(1),
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;